# Form implementation generated from reading ui file 'numbergame.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 350)
        MainWindow.setMinimumSize(QtCore.QSize(325, 350))
        MainWindow.setMaximumSize(QtCore.QSize(325, 350))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.checkButton.setGeometry(QtCore.QRect(70, 130, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.checkButton.setFont(font)
        self.checkButton.setObjectName("checkButton")
        self.guessNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.guessNumber.setGeometry(QtCore.QRect(70, 70, 185, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.guessNumber.setFont(font)
        self.guessNumber.setObjectName("guessNumber")
        self.instructionLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.instructionLabel.setGeometry(QtCore.QRect(30, 180, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.instructionLabel.setFont(font)
        self.instructionLabel.setObjectName("instructionLabel")
        self.hints = QtWidgets.QLabel(parent=self.centralwidget)
        self.hints.setEnabled(True)
        self.hints.setGeometry(QtCore.QRect(30, 220, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.hints.setFont(font)
        self.hints.setObjectName("hints")
        self.gameTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.gameTitle.setGeometry(QtCore.QRect(30, 0, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.gameTitle.setFont(font)
        self.gameTitle.setObjectName("gameTitle")
        self.quitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(170, 130, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.quitButton.setFont(font)
        self.quitButton.setObjectName("quitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 325, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkButton.setText(_translate("MainWindow", "CHECK"))
        self.instructionLabel.setText(_translate("MainWindow", "Please guess a number between 1-100."))
        self.hints.setText(_translate("MainWindow", "Tries Remaining: 10"))
        self.gameTitle.setText(_translate("MainWindow", "Guess the Number Game"))
        self.quitButton.setText(_translate("MainWindow", "RESET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
